[build]
  command = "npm run build || echo 'no build step'"
  publish = "."

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["playwright-core", "playwright-aws-lambda"]

[functions."*"]
  timeout = 26
  memory = 1024

[[headers]]
  for = "/.netlify/functions/snapshot-pdf*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, OPTIONS"
