[build]
  command = "npm run build || echo 'no build step'"
  publish = "."

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["puppeteer-core", "@sparticuz/chromium"]
  # Penting: bundling semua file chromium (bin + shared libs)
  included_files = ["node_modules/@sparticuz/chromium/**/*"]

[functions."snapshot-pdf"]
  timeout = 26      # max untuk Netlify Functions sync
  memory = 2048



[[headers]]
  for = "/.netlify/functions/snapshot-pdf*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, OPTIONS"
